FROM ruby:latest

ENV RAILS_ENV="production"

ARG RUBYGEMS_VERSION=3.4.6

RUN mkdir /api
WORKDIR /api

COPY Gemfile /api/Gemfile
COPY Gemfile.lock /api/Gemfile.lock

RUN gem update --system ${RUBYGEMS_VERSION} && \
bundle install

COPY . /api

RUN ["apt-get", "update"]

COPY entrypoint.sh.production /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh.production
ENTRYPOINT ["entrypoint.sh.production"]

CMD ["rails", "server", "-e", "production", "-b", "0.0.0.0"]